CREATE TABLE LIVRO(
	ID VARCHAR(255) NOT NULL;
	TITULO VARCHAR(255) NOT NULL;
	ISBN VARCHAR(255) NOT NULL,
	AUTOR VARCHAR(255) NOT NULL,
	CONSTRAINT PRIMARY KEY (ID)
);

CREATE TABLE ALUNO(
	MATRICULA VARCHAR(255) NOT NULL,
	CURSO VARCHAR(255) NOT NULL,
	PERIODO VARCHAR(255) NOT NULL,
	TURNO VARCHAR(255) NOT NULL,
	CONSTRAINT PRIMARY KEY (MATRICULA)
)